### ISSUE TITLE
xvega not working on Linux if installed from conda-forge

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/xvega#11] opened 2020-09-23 15:02 UTC
Trying on my ubuntu 20. All I did was creating an environment and running:

`mamba install -c conda-forge xtl xproperty nlohmann_json compilers jupyterlab`

`mamba list`:

```
# packages in environment at /home/mariana/miniconda3/envs/xvega:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
argon2-cffi               20.1.0           py36h7b6447c_1  
attrs                     20.2.0                     py_0  
backcall                  0.2.0                      py_0  
binutils                  2.33.1               h53a641e_7  
binutils_impl_linux-64    2.33.1               he6710b0_7  
binutils_linux-64         2.33.1              h9595d00_15  
bleach                    3.2.1                      py_0  
brotlipy                  0.7.0           py36h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
c-compiler                1.1.1                h516909a_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
cffi                      1.14.3           py36he30daa8_0  
chardet                   3.0.4                 py36_1003  
clang_variant             1.0                  cling_v0.7    conda-forge
clangdev                  5.0.0             h5d5d61b_1008    conda-forge
cling                     0.7                  he513fc3_1    conda-forge
cmake                     3.18.2               h5c55442_0    conda-forge
compilers                 1.1.1                         0    conda-forge
cppzmq                    4.6.0                hc9558a2_0    conda-forge
cryptography              3.1              py36h1ba5d50_0  
cxx-compiler              1.1.1                hc9558a2_0    conda-forge
dbus                      1.13.16              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py36_0  
expat                     2.2.9                he6710b0_2  
fontconfig                2.13.1            he4413a7_1000    conda-forge
fortran-compiler          1.1.1                he991be0_0    conda-forge
freetype                  2.10.2               h5ab3b9f_0  
gcc_impl_linux-64         7.3.0                habb00fd_1  
gcc_linux-64              7.3.0               h553295d_15  
gfortran_impl_linux-64    7.3.0                hdf63c60_1  
gfortran_linux-64         7.3.0               h553295d_15  
glib                      2.65.0               h3eb4bd4_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
gxx_impl_linux-64         7.3.0                hdf63c60_1  
gxx_linux-64              7.3.0               h553295d_15  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
importlib-metadata        1.7.0                    py36_0  
importlib_metadata        1.7.0                         0  
ipykernel                 5.3.4            py36h5ca1d4c_0  
ipython                   7.16.1           py36h5ca1d4c_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                7.5.1                      py_0  
jedi                      0.17.2                   py36_0  
jinja2                    2.11.2                     py_0  
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                    py36_0  
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            6.1.6                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py36_0  
jupyterlab                2.2.8                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0  
kernel-headers_linux-64   2.6.32              h77966d4_13    conda-forge
krb5                      1.18.2               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libuv                     1.39.0               h7b6447c_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               he19cac6_1  
markupsafe                1.1.1            py36h7b6447c_0  
mistune                   0.8.4            py36h7b6447c_0  
nbconvert                 5.6.1                    py36_0  
nbformat                  5.0.7                      py_0  
ncurses                   6.2                  he6710b0_1  
nlohmann_json             3.7.3                he1b5a44_1    conda-forge
notebook                  6.1.1                    py36_0  
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.4                       py_0  
pandoc                    2.10.1                        0  
pandocfilters             1.4.2                    py36_1  
parso                     0.7.0                      py_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pip                       20.2.2                   py36_0  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.7                      py_0  
prompt_toolkit            3.0.7                         0  
ptyprocess                0.6.0                    py36_0  
pugixml                   1.10                 he1b5a44_1    conda-forge
pycparser                 2.20                       py_2  
pygments                  2.7.1                      py_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py36h05f1152_2  
pyrsistent                0.17.3           py36h7b6447c_0  
pysocks                   1.7.1                    py36_0  
python                    3.6.12               hcff3b4d_2  
python-dateutil           2.8.1                      py_0  
python_abi                3.6                     1_cp36m    conda-forge
pyzmq                     19.0.2           py36he6710b0_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                     py_0  
rhash                     1.4.0                h1ba5d50_0  
send2trash                1.5.0                    py36_0  
setuptools                49.6.0                   py36_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               h62c20be_0  
sysroot_linux-64          2.12                h77966d4_13    conda-forge
terminado                 0.8.3                    py36_0  
testpath                  0.4.4                      py_0  
tk                        8.6.10               hbc83047_0  
tornado                   6.0.4            py36h7b6447c_1  
traitlets                 4.3.3                    py36_0  
urllib3                   1.25.10                    py_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py36_1  
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py36_0  
xeus                      0.24.1               h4d8c418_0    conda-forge
xeus-cling                0.10.0               he513fc3_0    conda-forge
xproperty                 0.10.3               hc9558a2_0    conda-forge
xtl                       0.6.19               hc9558a2_0    conda-forge
xvega                     0.0.2                hc9558a2_0    conda-forge
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.2                he6710b0_3  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h7b6447c_3  

```

When I run the `demo.ipynb` I get the following:

```
IncrementalExecutor::executeFunction: symbol '_ZN2xv13populate_dataERN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS0_14adl_serializerEEERKNS_5ChartE' unresolved while linking function '_GLOBAL__sub_I_cling_module_5'!
You are probably missing the definition of xv::populate_data(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>&, xv::Chart const&)
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN2xv18populate_encodingsERN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS0_14adl_serializerEEERKNS_5ChartE' unresolved while linking function '_GLOBAL__sub_I_cling_module_5'!
You are probably missing the definition of xv::populate_encodings(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>&, xv::Chart const&)
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN2xv19populate_selectionsERN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS0_14adl_serializerEEERKNS_5ChartE' unresolved while linking function '_GLOBAL__sub_I_cling_module_5'!
You are probably missing the definition of xv::populate_selections(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>&, xv::Chart const&)
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN2xv14populate_marksERN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS0_14adl_serializerEEERKNS_5ChartE' unresolved while linking function '_GLOBAL__sub_I_cling_module_5'!
You are probably missing the definition of xv::populate_marks(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>&, xv::Chart const&)
Maybe you need to load the corresponding shared library?
```

Also I think either `xvega` should depend on `xeus-cling`, since it's not possible to use it if you don't have it, or we should mention it somewhere on the readme.

**Comment by marimeireles** [comment] 2020-09-23 15:09
It works fine if I build from source @madhur-tandon 
Thanks for the help!

**Comment by madhur-tandon** [comment] 2020-09-23 15:16
Yes, It's basically missing the `libxvega` binary. I will try to reproduce it (but will try on a Mac). I kinda forgot to test it by installing from `conda-forge` and only tested it by building from source since I was too busy developing it xD

**Comment by madhur-tandon** [comment] 2020-10-09 07:34
@marimeireles This is probably fixed but it would be great if you could give a confirmation for this.
In a fresh environment, you can install `xeus-cling jupyterlab xproperty xvega` and try running the notebook.

If it works for you, we can probably close this issue / or wait for some more people to confirm.

**Comment by marimeireles** [comment] 2020-10-09 08:22
Yeah, sure! :)
I'm outside of my mac, but I'll test it on my linux. One sec =)

**Comment by madhur-tandon** [comment] 2020-10-12 02:42
Closing this as it's fixed by the great @SylvainCorlay :)

**Closed by madhur-tandon** 2020-10-12 02:42 UTC
